[package]
name = "test-for-each-example"
version = "1.0.0"
edition.workspace = true
publish = false

[lib]
proc-macro = true

[dependencies]
camino.workspace = true
proc-macro2 = "1.0.59"
quote = "1.0.33"
syn = { version = "2.0.29", features = ["full", "extra-traits"] }
