[package]
name = "scarb-test-support"
version = "1.0.0"
edition.workspace = true
publish = false

[features]
default = []
scarb-config = ["dep:scarb"]
proc-macro-server = ["dep:scarb-proc-macro-server-types"]

[dependencies]
anyhow.workspace = true
assert_fs.workspace = true
axum.workspace = true
camino.workspace = true
clap.workspace = true
data-encoding.workspace = true
dunce.workspace = true
indoc.workspace = true
itertools.workspace = true
scarb = { path = "../../scarb", default-features = false, optional = true }
scarb-build-metadata = { path = "../scarb-build-metadata" }
scarb-proc-macro-server-types = { path = "../scarb-proc-macro-server-types", optional = true }
scarb-ui = { path = "../scarb-ui" }
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
snapbox.workspace = true
tokio.workspace = true
toml_edit.workspace = true
tower-http.workspace = true
url.workspace = true
predicates.workspace = true
expect-test.workspace = true
walkdir.workspace = true

[package.metadata.cargo-machete]
ignored = ["dunce"]
