[package]
name = "dependencies"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git" }
