[package]
name = "scarb-manifest-schema-gen"
version = "1.0.0"
publish = false
description = ""
readme = "README.md"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true


[dependencies]
schemars.workspace = true
serde_json.workspace = true
scarb = { path = "../../scarb" }
scarb-manifest-schema = { path = "../scarb-manifest-schema" }
indoc.workspace = true
