[package]
name = "scarb-ui"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
camino.workspace = true
clap.workspace = true
console.workspace = true
indicatif.workspace = true
indoc.workspace = true
scarb-metadata = { version = "*", path = "../../scarb-metadata" }
serde.workspace = true
serde_json.workspace = true
