[package]
name = "scarb-ui"
version = "0.1.3"
edition.workspace = true

authors.workspace = true
categories = ["development-tools"]
description = "Terminal user interface primitives used by Scarb and its extensions"
homepage.workspace = true
keywords = ["scarb"]
license.workspace = true
readme = "README.md"
repository.workspace = true

[dependencies]
anyhow.workspace = true
camino.workspace = true
clap.workspace = true
console.workspace = true
indicatif.workspace = true
scarb-metadata = { version = "1", path = "../../scarb-metadata" }
serde.workspace = true
serde_json.workspace = true
smol_str.workspace = true
